name = "dfr-trigger"
main = "src/index.ts"
compatibility_date = "2025-07-18"

[[d1_databases]]
binding = "DB"
database_name = "dfr-trigger-db"
database_id = ""

[[kv_namespaces]]
binding = "KV"
id = ""

[observability]
enabled = true

[env.production]
vars = { ENVIRONMENT = "production" }