#!/bin/bash
# Auto-generated by publish skill — 启动/重启应用
# 反复执行 = 重启。pod 重启时由平台直接触发：
#   bash .publish/start.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKEND_DIR="$PROJECT_ROOT"

PORT="${PORT:-8081}"
HEALTH_URL="http://127.0.0.1:$PORT/api/health"
LOG_FILE="$SCRIPT_DIR/backend.log"
PID_FILE="$SCRIPT_DIR/backend.pid"

# ===== 0a) 依赖自检 =====
# python + uv 在镜像内，无需额外检查

# ===== 0b) 拉起 service =====
# 无 service 依赖

# 1) 停旧后端
if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  OLD_PID=$(cat "$PID_FILE")
  echo "[start] stopping old backend PID=$OLD_PID"
  kill "$OLD_PID" 2>/dev/null || true
  for _ in $(seq 1 10); do kill -0 "$OLD_PID" 2>/dev/null || break; sleep 1; done
  kill -0 "$OLD_PID" 2>/dev/null && kill -9 "$OLD_PID" 2>/dev/null || true
fi
rm -f "$PID_FILE"

# 兜底：清占用端口进程
PORT_PID=$(ss -tlnp 2>/dev/null | awk -v port="$PORT" '$4 ~ ":" port {print $7}' | grep -oE 'pid=[0-9]+' | head -1 | cut -d= -f2)
if [ -n "$PORT_PID" ]; then
  echo "[start] port $PORT held by PID=$PORT_PID, killing"
  kill -9 "$PORT_PID" 2>/dev/null || true; sleep 1
fi

# 2) 启动后端
echo "[start] launching backend..."
(
  set -e
  source "$SCRIPT_DIR/runtime.env"
  [ -f "$PROJECT_ROOT/.env" ] && source "$PROJECT_ROOT/.env"
  [ -f "$BACKEND_DIR/.env" ] && source "$BACKEND_DIR/.env"
  export PORT=$PORT
  cd "$BACKEND_DIR"
  setsid uv run --no-sync uvicorn app.main:app --host 0.0.0.0 --port "$PORT" --no-proxy-headers < /dev/null >> "$LOG_FILE" 2>&1 &
  echo $! > "$PID_FILE"
)
NEW_PID=$(cat "$PID_FILE")
echo "[start] backend launched PID=$NEW_PID, log=$LOG_FILE"

# 3) 健康检查
echo "[start] waiting for $HEALTH_URL ..."
for i in $(seq 1 30); do
  if curl -fsS -m 2 "$HEALTH_URL" >/dev/null 2>&1; then
    echo "[start] backend ready (took $((i*2))s)"
    break
  fi
  if ! kill -0 "$NEW_PID" 2>/dev/null; then
    echo "[start] backend process exited, see $LOG_FILE"
    tail -20 "$LOG_FILE"; exit 1
  fi
  if [ "$i" -eq 30 ]; then
    echo "[start] health check timed out after 60s"
    tail -40 "$LOG_FILE"; exit 1
  fi
  sleep 2
done

echo "[start] OK: http://127.0.0.1:$PORT (PID=$NEW_PID)"
